"use client";

import { useMemo, useState, type ReactElement } from "react";
import { useParams } from "next/navigation";
import { Download, Eye, Filter, MoreHorizontal, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";

type SectionConfig = { title: string; subtitle: string; columns: string[]; rows: string[][]; filters: string[] };

const configs: Record<string, SectionConfig> = {
  users: section("Utilisateurs", "Gere les comptes, roles et acces de la plateforme.", ["ID", "Utilisateur", "Email", "Role", "Statut", "Inscription"], [["#1048", "Nexy_Gamer", "jace@example.com", "Utilisateur", "Actif", "12 juin 2026"], ["#1047", "AstraNova", "nova@example.com", "Moderateur", "Actif", "11 juin 2026"], ["#1046", "BR_King", "king@example.com", "Utilisateur", "Inactif", "9 juin 2026"]], ["Tous", "Actifs", "Inactifs", "Bannis"]),
  players: section("Joueurs", "Profils gaming, identifiants et performances.", ["ID", "Pseudo", "Jeu principal", "ID joueur", "Rang", "Equipe", "Points"], [["#P208", "Nexy_Gamer", "Free Fire", "2272704178", "Bronze I", "Astral Elite", "1 280"], ["#P207", "PUBGMaster", "PUBG Mobile", "518420081", "Ace", "Nova Squad", "2 940"]], ["Tous les jeux", "Free Fire", "PUBG", "Fortnite"]),
  roles: section("Roles & permissions", "Controle fin des droits accordes a chaque equipe.", ["Role", "Membres", "Utilisateurs", "Tournois", "Boutique", "Paiements", "Logs"], [["Super Admin", "1", "Complet", "Complet", "Complet", "Complet", "Oui"], ["Moderateur", "4", "Lecture", "Gestion", "Lecture", "Non", "Non"], ["Support client", "3", "Lecture", "Non", "Commandes", "Lecture", "Non"]], ["Tous", "Administration", "Moderation", "Support"]),
  tournaments: section("Tournois", "Cree, programme et supervise les competitions.", ["Tournoi", "Jeu", "Format", "Participants", "Prize pool", "Date", "Statut"], [["Astral Free Fire Cup", "Free Fire", "Squad", "128 / 256", "250 000 XOF", "20 juin 2026", "A venir"], ["PUBG Mobile League", "PUBG", "Equipe", "46 / 64", "150 000 XOF", "28 juin 2026", "Brouillon"]], ["Tous", "Brouillon", "A venir", "En cours", "Termine"]),
  participations: section("Participations", "Valide les inscriptions et les paiements tournoi.", ["Joueur / equipe", "Tournoi", "Format", "Paiement", "Inscription", "Statut"], [["Team Nova", "Astral Free Fire Cup", "Squad", "Paye", "12 juin 2026", "Valide"], ["BR_King", "Solo Rush", "Solo", "En attente", "13 juin 2026", "A verifier"]], ["Toutes", "Validees", "En attente", "Refusees"]),
  registrations: section("Participations", "Valide les inscriptions et les paiements tournoi.", ["Joueur / equipe", "Tournoi", "Paiement", "Date", "Statut"], [["Team Nova", "Astral Free Fire Cup", "Paye", "12 juin 2026", "Valide"]], ["Toutes", "Validees", "En attente"]),
  matches: section("Matchs", "Programme et valide les resultats des rencontres.", ["Match", "Tournoi", "Equipe A", "Equipe B", "Score", "Heure", "Statut"], [["#M-081", "PUBG Mobile League", "Team Nova", "Astral Elite", "-", "20:30", "Programme"], ["#M-080", "FF Cup", "Rush Togo", "Lome Kings", "3 - 1", "Termine", "Valide"]], ["Tous", "Programmes", "Termines", "A valider"]),
  rankings: section("Classements", "Compare les performances par jeu et tournoi.", ["Rang", "Joueur / equipe", "Jeu", "Victoires", "Kills", "Points", "Ratio"], [["1", "Team Nova", "Free Fire", "14", "186", "4 820", "3.8"], ["2", "Astral Elite", "PUBG", "11", "142", "4 260", "3.2"]], ["General", "Free Fire", "PUBG", "Tournoi"]),
  products: section("Produits", "Catalogue, prix, marges et disponibilite fournisseur.", ["Produit", "Categorie", "Prix achat", "Prix vente", "Marge", "Stock", "Statut"], [["60 UC PUBG Mobile", "Top Up", "0,78 USD", "0,95 USD", "21,8 %", "Disponible", "Actif"], ["Garena Free Fire", "Gift Card", "0,72 USD", "0,89 USD", "23,6 %", "Disponible", "Actif"]], ["Tous", "Top Up", "Gift Cards", "Actifs"]),
  orders: section("Commandes", "Suis les paiements et la livraison fournisseur.", ["Commande", "Client", "Produit", "Montant", "Paiement", "Date", "Statut"], [["AG-260613-184", "Nexy_Gamer", "PUBG 325 UC", "4,80 USD", "Mobile Money", "13 juin 2026", "Livre"], ["AG-260613-183", "AstraNova", "Free Fire 530", "5,20 USD", "Carte", "13 juin 2026", "En cours"]], ["Toutes", "Payees", "En cours", "Livrees", "Echouees"]),
  transactions: section("Transactions", "Historique financier et rapprochement des paiements.", ["Reference", "Client", "Methode", "Montant", "Devise", "Date", "Statut"], [["MON-8F21A", "Nexy_Gamer", "TMoney", "3 150", "XOF", "13 juin 2026", "Succes"], ["MON-8F219", "AstraNova", "Carte", "8,40", "USD", "13 juin 2026", "En attente"]], ["Toutes", "Succes", "En attente", "Echecs"]),
  payments: section("Transactions", "Historique financier et rapprochement des paiements.", ["Reference", "Client", "Methode", "Montant", "Date", "Statut"], [["MON-8F21A", "Nexy_Gamer", "TMoney", "3 150 XOF", "13 juin 2026", "Succes"]], ["Toutes", "Succes", "En attente"]),
  calendar: section("Calendrier", "Vue centralisee des tournois, lives et promotions.", ["Evenement", "Type", "Debut", "Fin", "Canal", "Statut"], [["Astral Free Fire Cup", "Tournoi", "20 juin, 18:00", "20 juin, 22:00", "Site + Discord", "Programme"], ["Live tirage au sort", "Live", "18 juin, 20:00", "18 juin, 21:00", "YouTube", "Programme"]], ["Tous", "Tournois", "Lives", "Promotions"]),
  pages: section("Pages du site", "Edite les contenus institutionnels et juridiques.", ["Page", "Slug", "Derniere modification", "Auteur", "Statut"], [["A propos", "/a-propos", "10 juin 2026", "Admin Astral", "Publie"], ["Conditions d'utilisation", "/conditions", "8 juin 2026", "Admin Astral", "Publie"]], ["Toutes", "Publiees", "Brouillons"]),
  banners: section("Bannieres", "Pilote les visuels promotionnels du site.", ["Banniere", "Position", "Lien", "Debut", "Fin", "Statut"], [["Free Fire Diamonds", "Accueil", "/product/1428", "1 juin", "30 juin", "Active"], ["PUBG Mobile UC", "Boutique", "/product/1520", "10 juin", "24 juin", "Active"]], ["Toutes", "Accueil", "Boutique", "Tournois"]),
  integrations: section("API & integrations", "Surveille les fournisseurs, paiements et services externes.", ["Service", "Categorie", "Environnement", "Dernier appel", "Latence", "Statut"], [["Games Kinbo", "Fournisseur", "Production", "Il y a 2 min", "284 ms", "Connecte"], ["Moneroo", "Paiement", "Sandbox", "Il y a 8 min", "412 ms", "Connecte"], ["YouTube Data API", "Contenu", "Production", "Il y a 1 h", "196 ms", "Connecte"], ["Blogger API", "Contenu", "Production", "Il y a 3 h", "221 ms", "Connecte"]], ["Toutes", "Fournisseurs", "Paiements", "Contenu"]),
  settings: section("Parametres", "Configuration globale de la plateforme.", ["Parametre", "Valeur", "Portee", "Modification"], [["Nom du site", "Astral4Gamer", "Global", "Aujourd'hui"], ["Devise principale", "XOF", "Boutique", "Aujourd'hui"], ["Marge par defaut", "12 %", "Produits", "12 juin 2026"], ["Mode maintenance", "Desactive", "Global", "10 juin 2026"]], ["General", "Boutique", "Notifications", "Securite"]),
  logs: section("Journaux d'activites", "Audit des actions admin et erreurs techniques.", ["Date", "Admin", "Action", "Ressource", "Adresse IP", "Resultat"], [["13 juin 2026 14:28", "Admin Astral", "Connexion", "Admin Panel", "2.24.14.212", "Succes"], ["13 juin 2026 14:12", "Systeme", "Synchronisation", "Catalogue", "Serveur", "Succes"]], ["Tous", "Connexions", "Modifications", "Erreurs API"])
};

configs.news = section("Actualites", "Redige et programme les annonces Astral4Gamer.", ["Titre", "Categorie", "Auteur", "Publication", "Canal", "Statut"], [["Astral Free Fire Cup ouvre ses inscriptions", "Tournoi", "Admin Astral", "13 juin 2026", "Site + Blogger", "Publie"], ["Nouveaux top ups disponibles", "Boutique", "Admin Astral", "14 juin 2026", "Site", "Brouillon"]], ["Toutes", "Publiees", "Brouillons"]);
configs.coupons = section("Codes promo", "Cree et analyse les promotions de la boutique.", ["Code", "Type", "Valeur", "Utilisations", "Expiration", "Cible", "Statut"], [["NEWCU", "Pourcentage", "5 %", "48 / 500", "30 juin 2026", "Tous les produits", "Actif"], ["FFCUP10", "Pourcentage", "10 %", "12 / 100", "20 juin 2026", "Free Fire", "Actif"]], ["Tous", "Actifs", "Expires"]);

function section(title: string, subtitle: string, columns: string[], rows: string[][], filters: string[]): SectionConfig { return { title, subtitle, columns, rows, filters }; }

export default function AdminSectionPage() {
  const params = useParams<{ section: string }>();
  const key = String(params.section ?? "");
  const config = configs[key] ?? section("Module admin", "Ce module est pret a recevoir ses donnees.", ["Element", "Description", "Statut"], [[key, "Configuration en cours", "Disponible"]], ["Tous"]);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState(config.filters[0]);
  const [modal, setModal] = useState(false);
  const rows = useMemo(() => config.rows.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase())), [config.rows, query]);

  return <AdminShell title={config.title} subtitle={config.subtitle}>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
      <div className="flex flex-1 flex-wrap gap-2">
        <label className="flex h-11 min-w-[230px] flex-1 items-center gap-2 rounded-lg border border-white/10 bg-white/[0.04] px-3 text-slate-400 md:max-w-md"><Search className="h-4 w-4" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm text-white outline-none" placeholder={`Rechercher dans ${config.title.toLowerCase()}...`} /></label>
        <label className="flex h-11 items-center gap-2 rounded-lg border border-white/10 bg-white/[0.04] px-3 text-sm text-slate-300"><Filter className="h-4 w-4" /><select value={filter} onChange={(e) => setFilter(e.target.value)} className="bg-transparent outline-none">{config.filters.map((item) => <option className="bg-[#101827]" key={item}>{item}</option>)}</select></label>
      </div>
      <button className="inline-flex h-11 items-center gap-2 rounded-lg border border-white/10 px-4 text-sm text-slate-200"><Download className="h-4 w-4" />Exporter</button>
      <button onClick={() => setModal(true)} className="inline-flex h-11 items-center gap-2 rounded-lg bg-violet-600 px-4 text-sm font-semibold shadow-lg shadow-violet-950/40"><Plus className="h-4 w-4" />Ajouter</button>
    </div>

    <section className="overflow-hidden rounded-lg border border-white/10 bg-white/[0.035] shadow-2xl shadow-black/10">
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-left text-sm"><thead className="border-b border-white/10 bg-white/[0.035] text-[11px] uppercase tracking-wide text-slate-400"><tr>{config.columns.map((column) => <th key={column} className="px-4 py-4 font-medium">{column}</th>)}<th className="px-4 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-white/[0.07]">{rows.map((row, index) => <tr key={`${row[0]}-${index}`} className="transition hover:bg-violet-500/[0.06]">{row.map((cell, cellIndex) => <td key={cellIndex} className={`px-4 py-4 ${cellIndex === 0 ? "font-medium text-white" : "text-slate-300"}`}>{cellIndex === row.length - 1 ? <Status value={cell} /> : cell}</td>)}<td className="px-4 py-4"><div className="flex justify-end gap-1"><Action icon={<Eye />} label="Voir" /><Action icon={<Pencil />} label="Modifier" /><Action icon={<MoreHorizontal />} label="Plus" /></div></td></tr>)}</tbody></table></div>
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 px-4 py-3 text-xs text-slate-400"><span>{rows.length} resultat{rows.length > 1 ? "s" : ""}</span><div className="flex gap-1"><button className="rounded-md border border-white/10 px-3 py-2">Precedent</button><button className="rounded-md bg-violet-600 px-3 py-2 text-white">1</button><button className="rounded-md border border-white/10 px-3 py-2">Suivant</button></div></footer>
    </section>

    {modal ? <div className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><section className="w-full max-w-lg rounded-lg border border-white/10 bg-[#111827] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Ajouter dans {config.title}</h2><p className="mt-1 text-xs text-slate-400">Complete les informations puis enregistre.</p></div><button onClick={() => setModal(false)} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{config.columns.slice(0, 4).map((column) => <label key={column} className="block"><span className="text-xs text-slate-400">{column}</span><input className="mt-2 h-11 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm outline-none focus:border-violet-500" /></label>)}</div><div className="mt-6 flex justify-end gap-2"><button onClick={() => setModal(false)} className="h-10 rounded-lg border border-white/10 px-4 text-sm">Annuler</button><button onClick={() => setModal(false)} className="h-10 rounded-lg bg-violet-600 px-4 text-sm font-semibold">Enregistrer</button></div></section></div> : null}
  </AdminShell>;
}

function Status({ value }: { value: string }) { const good = /actif|active|succes|livre|valide|connecte|publie|disponible/i.test(value); const bad = /echec|banni|refuse|annule/i.test(value); return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-medium ${good ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : bad ? "border-red-400/20 bg-red-400/10 text-red-300" : "border-amber-400/20 bg-amber-400/10 text-amber-200"}`}>{value}</span>; }
function Action({ icon, label }: { icon: ReactElement; label: string }) { return <button title={label} className="grid h-8 w-8 place-items-center rounded-md text-slate-400 transition hover:bg-white/10 hover:text-white"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span></button>; }
