<?php

return [
    'webhook' => [
        'secret' => env('WEBHOOK_SECRET', 'change-me'),
    ],
    'suppliers' => [
        'item4gamer' => [
            'key' => env('ITEM4GAMER_KEY'),
            'key_header' => env('ITEM4GAMER_KEY_HEADER', 'api-key'),
            'force_ipv4' => env('ITEM4GAMER_FORCE_IPV4', true),
            'category_ids' => array_values(array_filter(array_map('trim', explode(',', env('ITEM4GAMER_CATEGORY_IDS', ''))))),
            'per_page' => env('ITEM4GAMER_PER_PAGE', 100),
            'max_pages' => env('ITEM4GAMER_MAX_PAGES', 20),
            'base_url' => env('ITEM4GAMER_BASE_URL', 'https://item4gamer.com/wp-json/reseller/v1'),
            'site_url' => env('ITEM4GAMER_SITE_URL', 'https://item4gamer.com'),
            'endpoints' => [
                'categories' => env('ITEM4GAMER_CATEGORIES_ENDPOINT', '/product/get-categories'),
                'products' => env('ITEM4GAMER_PRODUCTS_ENDPOINT', '/product/get-products'),
                'variations' => env('ITEM4GAMER_VARIATIONS_ENDPOINT', '/product/get-variations'),
                'add_order' => '/order/add-order',
                'get_order' => '/order/get-order',
                'balance' => '/get-balance',
            ],
        ],
        'fazercards' => [
            'key' => env('FAZERCARDS_KEY'),
            'base_url' => env('FAZERCARDS_BASE_URL', 'https://api.fzr.cards/api/v2'),
            'enabled' => env('FAZERCARDS_ENABLED', true),
            'sync_topups' => env('FAZERCARDS_SYNC_TOPUPS', true),
            'sync_giftcards' => env('FAZERCARDS_SYNC_GIFTCARDS', true),
            'sync_gamekeys' => env('FAZERCARDS_SYNC_GAMEKEYS', true),
            'sync_manual_services' => env('FAZERCARDS_SYNC_MANUAL_SERVICES', true),
            'page_limit' => env('FAZERCARDS_PAGE_LIMIT', 500),
            'max_pages' => env('FAZERCARDS_MAX_PAGES', 20),
        ],
        'seagm' => ['key' => env('SEAGM_KEY')],
        'unipin' => ['key' => env('UNIPIN_KEY')],
    ],
    'shop' => [
        'margin_percent' => env('SHOP_MARGIN_PERCENT', 30),
        'margin_fixed' => env('SHOP_MARGIN_FIXED', 0),
        'margin_minimum' => env('SHOP_MARGIN_MINIMUM', 0),
        'price_decimals' => env('SHOP_PRICE_DECIMALS', 2),
    ],
    'reseller' => [
        'panel_url' => env('RESELLER_PANEL_URL', 'https://www.astral4gamer.com/panel'),
        'default_margin_percent' => env('RESELLER_DEFAULT_MARGIN_PERCENT', 10),
        'minimum_topup' => env('RESELLER_MINIMUM_TOPUP', 10),
        'low_balance_threshold' => env('RESELLER_LOW_BALANCE_THRESHOLD', 10),
    ],
    'hlgaming' => [
        'useruid' => env('HLGAMING_USERUID'),
        'api_key' => env('HLGAMING_API_KEY'),
        'timeout' => env('HLGAMING_TIMEOUT', 12),
        'freefire' => [
            'account_endpoint' => env('HLGAMING_FREEFIRE_ACCOUNT_ENDPOINT', 'https://proapis.hlgamingofficial.com/main/games/freefire/account/api'),
            'validation_endpoint' => env('HLGAMING_FREEFIRE_VALIDATION_ENDPOINT', 'https://proapis.hlgamingofficial.com/main/games/freefire/validation/api'),
            'meta_endpoint' => env('HLGAMING_FREEFIRE_META_ENDPOINT', 'https://proapis.hlgamingofficial.com/main/games/freefire/meta/api'),
            'likes_endpoint' => env('HLGAMING_FREEFIRE_LIKES_ENDPOINT'),
            'reward_endpoint' => env('HLGAMING_FREEFIRE_REWARD_ENDPOINT', 'https://proapis.hlgamingofficial.com/main/games/freefire/reward/api'),
            'default_region' => env('HLGAMING_FREEFIRE_DEFAULT_REGION', 'me'),
            'likes_daily_limit' => env('FREEFIRE_LIKES_DAILY_LIMIT', 100),
            'likes_price_xof' => env('FREEFIRE_LIKES_PRICE_XOF', 300),
        ],
        'genshin' => [
            'endpoint' => env('HLGAMING_GENSHIN_ENDPOINT', 'https://apis.hlgamingofficial.com/main/games/genshin/account/api'),
        ],
        'upcoming' => [
            'endpoint' => env('HLGAMING_UPCOMING_ENDPOINT', 'https://apis.hlgamingofficial.com/main/games/others/upcoming/api'),
        ],
    ],
    'freefire' => [
        'provider' => env('FREEFIRE_PROVIDER', 'gameskinbo'),
    ],
    'gameskinbo' => [
        'api_key' => env('GAMESKINBO_API_KEY'),
        'timeout' => env('GAMESKINBO_TIMEOUT', 12),
        'freefire' => [
            'endpoint' => env('GAMESKINBO_FREEFIRE_ENDPOINT', 'https://api.gameskinbo.com/ff-info/get'),
        ],
    ],
    'callofdutyapi' => [
        'key' => env('CALLOFDUTY_API_KEY'),
        'base_url' => env('CALLOFDUTY_API_BASE_URL', 'https://v1.callofdutyapi.com'),
        'timeout' => env('CALLOFDUTY_API_TIMEOUT', 12),
        'cache_minutes' => env('CALLOFDUTY_API_CACHE_MINUTES', 4320),
        'miss_cache_minutes' => env('CALLOFDUTY_API_MISS_CACHE_MINUTES', 60),
    ],
    'fortnite' => [
        'key' => env('FORTNITE_API_KEY'),
        'base_url' => env('FORTNITE_API_BASE_URL', 'https://fortnite-api.com'),
        'timeout' => env('FORTNITE_API_TIMEOUT', 12),
        'cache_minutes' => env('FORTNITE_API_CACHE_MINUTES', 4320),
    ],
    'pubg' => [
        'key' => env('PUBG_API_KEY', env('PUBG_API_TOKEN')),
        'base_url' => env('PUBG_API_BASE_URL', 'https://api.pubg.com'),
        'timeout' => env('PUBG_API_TIMEOUT', 12),
        'profile_cache_minutes' => env('PUBG_PROFILE_CACHE_MINUTES', 4320),
        'match_cache_minutes' => env('PUBG_MATCH_CACHE_MINUTES', 4320),
        'leaderboard_cache_minutes' => env('PUBG_LEADERBOARD_CACHE_MINUTES', 60),
    ],
    'discord' => [
        'enabled' => env('DISCORD_NOTIFICATIONS_ENABLED', false),
        'bot_token' => env('ASTRAL_BOT_BACKEND_TOKEN'),
        'username' => env('DISCORD_WEBHOOK_USERNAME', 'Astral4Gamer'),
        'avatar_url' => env('DISCORD_WEBHOOK_AVATAR_URL'),
        'timeout' => env('DISCORD_WEBHOOK_TIMEOUT', 8),
        'webhooks' => [
            'tournaments' => env('DISCORD_TOURNAMENTS_WEBHOOK_URL'),
            'streams' => env('DISCORD_STREAMS_WEBHOOK_URL'),
            'events' => env('DISCORD_EVENTS_WEBHOOK_URL', env('DISCORD_STREAMS_WEBHOOK_URL')),
            'lives' => env('DISCORD_LIVES_WEBHOOK_URL', env('DISCORD_STREAMS_WEBHOOK_URL')),
            'community' => env('DISCORD_COMMUNITY_WEBHOOK_URL', env('DISCORD_ANNOUNCEMENTS_WEBHOOK_URL')),
            'announcements' => env('DISCORD_ANNOUNCEMENTS_WEBHOOK_URL'),
            'promotions' => env('DISCORD_PROMOTIONS_WEBHOOK_URL'),
            'partners' => env('DISCORD_PARTNERS_WEBHOOK_URL', env('DISCORD_PARTNER_WEBHOOK_URL')),
            'support' => env('DISCORD_SUPPORT_WEBHOOK_URL'),
        ],
    ],
    'payments' => [
        'cinetpay' => ['key' => env('CINETPAY_KEY')],
        'fedapay' => ['key' => env('FEDAPAY_KEY')],
        'paydunya' => ['key' => env('PAYDUNYA_KEY')],
        'moneroo' => [
            'secret_key' => env('MONEROO_SECRET_KEY'),
            'public_key' => env('MONEROO_PUBLIC_KEY'),
            'webhook_secret' => env('MONEROO_WEBHOOK_SECRET'),
            'base_url' => env('MONEROO_BASE_URL', 'https://api.moneroo.io'),
            'default_currency' => env('MONEROO_DEFAULT_CURRENCY', 'USD'),
            'default_methods' => array_values(array_filter(array_map('trim', explode(',', (string) env('MONEROO_DEFAULT_METHODS', ''))))),
            'methods_by_currency' => json_decode((string) env('MONEROO_METHODS_BY_CURRENCY', '{}'), true) ?: [],
            'return_url' => env('MONEROO_RETURN_URL', env('APP_BACKEND_URL', env('APP_URL', 'http://localhost:8000')).'/api/payments/moneroo/return'),
            'frontend_return_url' => env('MONEROO_FRONTEND_RETURN_URL', env('APP_FRONTEND_URL', env('FRONTEND_URL', 'http://localhost:3000')).'/checkout/return'),
        ],
    ],
    'youtube' => [
        'key' => env('YOUTUBE_API_KEY'),
        'channel_id' => env('YOUTUBE_CHANNEL_ID'),
        'client_id' => env('YOUTUBE_CLIENT_ID'),
        'client_secret' => env('YOUTUBE_CLIENT_SECRET'),
        'redirect_uri' => env('YOUTUBE_REDIRECT_URI'),
        'frontend_url' => env('APP_FRONTEND_URL', env('FRONTEND_URL', 'http://localhost:3000')),
    ],
    'steam' => [
        'key' => env('STEAM_WEB_API_KEY'),
        'news_cache_minutes' => env('STEAM_NEWS_CACHE_MINUTES', 60),
        'news_apps' => [
            ['appid' => 730, 'name' => 'Counter-Strike 2', 'category' => 'FPS / Shooter'],
            ['appid' => 570, 'name' => 'Dota 2', 'category' => 'MOBA'],
            ['appid' => 578080, 'name' => 'PUBG', 'category' => 'Battle Royale'],
            ['appid' => 1172470, 'name' => 'Apex Legends', 'category' => 'Battle Royale'],
            ['appid' => 271590, 'name' => 'Grand Theft Auto V', 'category' => 'Action'],
            ['appid' => 1245620, 'name' => 'Elden Ring', 'category' => 'RPG'],
        ],
    ],
    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect_uri' => env('GOOGLE_REDIRECT_URI', env('APP_BACKEND_URL', env('APP_URL', 'http://localhost:8000')).'/api/auth/google/callback'),
        'frontend_url' => env('APP_FRONTEND_URL', env('FRONTEND_URL', 'http://localhost:3000')),
        'people_scopes' => array_values(array_filter(explode(' ', env('GOOGLE_PEOPLE_SCOPES', 'openid email profile https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email')))),
        'youtube_engagement_scopes' => array_values(array_filter(explode(' ', env('GOOGLE_YOUTUBE_ENGAGEMENT_SCOPES', 'https://www.googleapis.com/auth/youtube.force-ssl')))),
        'calendar' => [
            'id' => env('GOOGLE_TOURNAMENT_CALENDAR_ID'),
            'api_key' => env('GOOGLE_CALENDAR_API_KEY', env('GOOGLE_API_KEY')),
            'service_account_json' => env('GOOGLE_CALENDAR_SERVICE_ACCOUNT_JSON'),
            'timezone' => env('GOOGLE_TOURNAMENT_CALENDAR_TIMEZONE', 'UTC'),
            'slot_minutes' => env('TOURNAMENT_SLOT_MINUTES', 60),
            'step_minutes' => env('TOURNAMENT_SLOT_STEP_MINUTES', 60),
            'day_start' => env('TOURNAMENT_SLOT_DAY_START', '18:00'),
            'day_end' => env('TOURNAMENT_SLOT_DAY_END', '23:00'),
        ],
    ],
    'blogger' => [
        'blog_id' => env('BLOGGER_BLOG_ID'),
        'auto_publish' => env('BLOGGER_AUTO_PUBLISH', true),
        'labels' => array_values(array_filter(array_map('trim', explode(',', env('BLOGGER_LABELS', 'Free Fire,Tournoi,Esport,Astral4Gamer'))))),
        'oauth_scopes' => array_values(array_filter(explode(' ', env('GOOGLE_BLOGGER_SCOPES', 'https://www.googleapis.com/auth/blogger')))),
    ],
    'openai' => [
        'key' => env('OPENAI_API_KEY'),
    ],
    'obs' => [
        'websocket_url' => env('OBS_WEBSOCKET_URL'),
        'password' => env('OBS_WEBSOCKET_PASSWORD'),
    ],
];
