<?php

return [
    'webhook' => [
        'secret' => env('WEBHOOK_SECRET', 'change-me'),
    ],
    'suppliers' => [
        'item4gamer' => [
            'key' => env('ITEM4GAMER_KEY'),
            'key_header' => env('ITEM4GAMER_KEY_HEADER', 'api-key'),
            'force_ipv4' => env('ITEM4GAMER_FORCE_IPV4', true),
            'category_ids' => array_values(array_filter(array_map('trim', explode(',', env('ITEM4GAMER_CATEGORY_IDS', ''))))),
            'per_page' => env('ITEM4GAMER_PER_PAGE', 100),
            'max_pages' => env('ITEM4GAMER_MAX_PAGES', 20),
            'base_url' => env('ITEM4GAMER_BASE_URL', 'https://item4gamer.com/wp-json/reseller/v1'),
            'site_url' => env('ITEM4GAMER_SITE_URL', 'https://item4gamer.com'),
            'endpoints' => [
                'categories' => env('ITEM4GAMER_CATEGORIES_ENDPOINT', '/product/get-categories'),
                'products' => env('ITEM4GAMER_PRODUCTS_ENDPOINT', '/product/get-products'),
                'variations' => env('ITEM4GAMER_VARIATIONS_ENDPOINT', '/product/get-variations'),
                'add_order' => '/order/add-order',
                'get_order' => '/order/get-order',
                'balance' => '/get-balance',
            ],
        ],
        'fazercards' => [
            'key' => env('FAZERCARDS_KEY'),
            'base_url' => env('FAZERCARDS_BASE_URL', 'https://api.fzr.cards/api/v2'),
            'webhook_token' => env('FAZERCARDS_WEBHOOK_TOKEN'),
            'webhook_signing_secret' => env('FAZERCARDS_WEBHOOK_SIGNING_SECRET'),
            'enabled' => env('FAZERCARDS_ENABLED', true),
            'sync_topups' => env('FAZERCARDS_SYNC_TOPUPS', true),
            'sync_giftcards' => env('FAZERCARDS_SYNC_GIFTCARDS', true),
            'sync_gamekeys' => env('FAZERCARDS_SYNC_GAMEKEYS', true),
            'sync_manual_services' => env('FAZERCARDS_SYNC_MANUAL_SERVICES', true),
            'page_limit' => env('FAZERCARDS_PAGE_LIMIT', 500),
            'max_pages' => env('FAZERCARDS_MAX_PAGES', 20),
        ],
        'seagm' => ['key' => env('SEAGM_KEY')],
        'unipin' => ['key' => env('UNIPIN_KEY')],
    ],
    'shop' => [
        'margin_percent' => env('SHOP_MARGIN_PERCENT', 30),
        'margin_fixed' => env('SHOP_MARGIN_FIXED', 0),
        'margin_minimum' => env('SHOP_MARGIN_MINIMUM', 0),
        'price_decimals' => env('SHOP_PRICE_DECIMALS', 2),
        'first_purchase_discount_percent' => env('SHOP_FIRST_PURCHASE_DISCOUNT_PERCENT', 5),
        'first_purchase_discount_min_profit' => env('SHOP_FIRST_PURCHASE_DISCOUNT_MIN_PROFIT', 0.01),
    ],
    'reseller' => [
        'panel_url' => env('RESELLER_PANEL_URL', 'https://www.astral4gamer.com/panel'),
        'default_margin_percent' => env('RESELLER_DEFAULT_MARGIN_PERCENT', 10),
        'minimum_topup' => env('RESELLER_MINIMUM_TOPUP', 100),
        'low_balance_threshold' => env('RESELLER_LOW_BALANCE_THRESHOLD', 10),
        'express_enabled' => env('RESELLER_EXPRESS_ENABLED', true),
        'express_fee_percent' => env('RESELLER_EXPRESS_FEE_PERCENT', 10),
        'express_fee_minimum' => env('RESELLER_EXPRESS_FEE_MINIMUM', 5),
        'loan_margin_rate' => env('RESELLER_LOAN_MARGIN_RATE', 10),
        'loan_auto_approve' => env('RESELLER_LOAN_AUTO_APPROVE', true),
        'api_subscription_fee_xof' => env('RESELLER_API_SUBSCRIPTION_FEE_XOF', 8000),
        'api_subscription_fee_xaf' => env('RESELLER_API_SUBSCRIPTION_FEE_XAF', 8000),
        'api_subscription_fee_eur' => env('RESELLER_API_SUBSCRIPTION_FEE_EUR', 12.2),
        'api_subscription_fee_usd' => env('RESELLER_API_SUBSCRIPTION_FEE_USD', 13.1),
        'api_subscription_grace_days' => env('RESELLER_API_SUBSCRIPTION_GRACE_DAYS', 3),
        'api_subscription_start_date' => env('RESELLER_API_SUBSCRIPTION_START_DATE', '2026-07-01'),
    ],
    'hlgaming' => [
        'useruid' => env('HLGAMING_USERUID'),
        'api_key' => env('HLGAMING_API_KEY'),
        'timeout' => env('HLGAMING_TIMEOUT', 12),
        'freefire' => [
            'reward_endpoint' => env('HLGAMING_FREEFIRE_REWARD_ENDPOINT', 'https://proapis.hlgamingofficial.com/main/games/freefire/reward/api'),
        ],
        'genshin' => [
            'endpoint' => env('HLGAMING_GENSHIN_ENDPOINT', 'https://apis.hlgamingofficial.com/main/games/genshin/account/api'),
        ],
        'upcoming' => [
            'endpoint' => env('HLGAMING_UPCOMING_ENDPOINT', 'https://apis.hlgamingofficial.com/main/games/others/upcoming/api'),
        ],
    ],
    'freefire' => [
        'provider' => env('FREEFIRE_PROVIDER', 'external'),
        'likes_daily_limit' => env('FREEFIRE_LIKES_DAILY_LIMIT', 100),
        'likes_price_xof' => env('FREEFIRE_LIKES_PRICE_XOF', 300),
        'lookup' => [
            'api_key' => env('FREEFIRE_LOOKUP_API_KEY', env('GAMESKINBO_API_KEY')),
            'endpoint' => env('FREEFIRE_LOOKUP_ENDPOINT', env('GAMESKINBO_FREEFIRE_ENDPOINT')),
            'likes_endpoint' => env('FREEFIRE_LOOKUP_LIKES_ENDPOINT', env('GAMESKINBO_FREEFIRE_LIKES_ENDPOINT')),
            'default_region' => env('FREEFIRE_LOOKUP_DEFAULT_REGION', 'me'),
            'timeout' => env('FREEFIRE_LOOKUP_TIMEOUT', env('GAMESKINBO_TIMEOUT', 12)),
        ],
    ],
    'callofdutyapi' => [
        'key' => env('CALLOFDUTY_API_KEY'),
        'base_url' => env('CALLOFDUTY_API_BASE_URL', 'https://v1.callofdutyapi.com'),
        'timeout' => env('CALLOFDUTY_API_TIMEOUT', 12),
        'cache_minutes' => env('CALLOFDUTY_API_CACHE_MINUTES', 4320),
        'miss_cache_minutes' => env('CALLOFDUTY_API_MISS_CACHE_MINUTES', 60),
    ],
    'fortnite' => [
        'key' => env('FORTNITE_API_KEY'),
        'base_url' => env('FORTNITE_API_BASE_URL', 'https://fortnite-api.com'),
        'timeout' => env('FORTNITE_API_TIMEOUT', 12),
        'cache_minutes' => env('FORTNITE_API_CACHE_MINUTES', 4320),
    ],
    'pubg' => [
        'key' => env('PUBG_API_KEY', env('PUBG_API_TOKEN')),
        'base_url' => env('PUBG_API_BASE_URL', 'https://api.pubg.com'),
        'timeout' => env('PUBG_API_TIMEOUT', 12),
        'profile_cache_minutes' => env('PUBG_PROFILE_CACHE_MINUTES', 4320),
        'match_cache_minutes' => env('PUBG_MATCH_CACHE_MINUTES', 4320),
        'leaderboard_cache_minutes' => env('PUBG_LEADERBOARD_CACHE_MINUTES', 60),
    ],
    'startgg' => [
        'token' => env('STARTGG_API_TOKEN'),
        'base_url' => env('STARTGG_API_URL', 'https://api.start.gg/gql/alpha'),
        'timeout' => env('STARTGG_API_TIMEOUT', 15),
        'cache_minutes' => env('STARTGG_CACHE_MINUTES', 10),
    ],
    'discord' => [
        'enabled' => env('DISCORD_NOTIFICATIONS_ENABLED', false),
        'bot_token' => env('DISCORD_BOT_TOKEN', env('ASTRAL_BOT_BACKEND_TOKEN')),
        'backend_token' => env('ASTRAL_BOT_BACKEND_TOKEN', env('DISCORD_BOT_TOKEN')),
        'manual_fulfillment_admin_ids' => env('DISCORD_MANUAL_FULFILLMENT_ADMIN_IDS', env('DISCORD_OWNER_ID', '')),
        'username' => env('DISCORD_WEBHOOK_USERNAME', 'Astral4Gamer'),
        'avatar_url' => env('DISCORD_WEBHOOK_AVATAR_URL'),
        'timeout' => env('DISCORD_WEBHOOK_TIMEOUT', 8),
        'webhooks' => [
            'tournaments' => env('DISCORD_TOURNAMENTS_WEBHOOK_URL'),
            'tournament_registrations' => env('DISCORD_TOURNAMENT_REGISTRATIONS_WEBHOOK_URL'),
            'streams' => env('DISCORD_STREAMS_WEBHOOK_URL'),
            'events' => env('DISCORD_EVENTS_WEBHOOK_URL', env('DISCORD_STREAMS_WEBHOOK_URL')),
            'lives' => env('DISCORD_LIVES_WEBHOOK_URL', env('DISCORD_STREAMS_WEBHOOK_URL')),
            'community' => env('DISCORD_COMMUNITY_WEBHOOK_URL', env('DISCORD_ANNOUNCEMENTS_WEBHOOK_URL')),
            'announcements' => env('DISCORD_ANNOUNCEMENTS_WEBHOOK_URL'),
            'promotions' => env('DISCORD_PROMOTIONS_WEBHOOK_URL'),
            'partners' => env('DISCORD_PARTNERS_WEBHOOK_URL', env('DISCORD_PARTNER_WEBHOOK_URL')),
            'support' => env('DISCORD_SUPPORT_WEBHOOK_URL'),
        ],
        'channels' => [
            'announcements' => env('DISCORD_ANNOUNCEMENTS_CHANNEL_ID', env('DISCORD_WELCOME_CHANNEL_ID', '1521888575371612381')),
            'community' => env('DISCORD_COMMUNITY_CHANNEL_ID', '1521887196846755961'),
            'tournaments' => env('DISCORD_TOURNAMENT_CHANNEL_ID', env('DISCORD_TOURNAMENT_ANNOUNCEMENTS_CHANNEL_ID', '1521884680880914685')),
            'tournament_registrations' => env('DISCORD_TOURNAMENT_REGISTRATIONS_CHANNEL_ID', '1521885156430975116'),
            'events' => env('DISCORD_EVENTS_CHANNEL_ID', env('DISCORD_COMMUNITY_CHANNEL_ID', '1521887196846755961')),
            'lives' => env('DISCORD_LIVE_CHANNEL_ID', '1521887517249503363'),
            'streams' => env('DISCORD_LIVE_CHANNEL_ID', '1521887517249503363'),
            'promotions' => env('DISCORD_PROMOTIONS_CHANNEL_ID', '1521887930627391658'),
            'partners' => env('DISCORD_PARTNER_CHANNEL_ID'),
            'support' => env('DISCORD_SUPPORT_CHANNEL_ID', env('DISCORD_HELP_CHANNEL_ID', '1512238962083631114')),
        ],
    ],
    'payments' => [
        'cinetpay' => ['key' => env('CINETPAY_KEY')],
        'fedapay' => ['key' => env('FEDAPAY_KEY')],
        'paydunya' => ['key' => env('PAYDUNYA_KEY')],
        'moneroo' => [
            'secret_key' => env('MONEROO_SECRET_KEY'),
            'public_key' => env('MONEROO_PUBLIC_KEY'),
            'webhook_secret' => env('MONEROO_WEBHOOK_SECRET'),
            'webhook_token' => env('MONEROO_WEBHOOK_TOKEN'),
            'base_url' => env('MONEROO_BASE_URL', 'https://api.moneroo.io'),
            'default_currency' => env('MONEROO_DEFAULT_CURRENCY', 'USD'),
            'default_methods' => array_values(array_filter(array_map('trim', explode(',', (string) env('MONEROO_DEFAULT_METHODS', ''))))),
            'methods_by_currency' => json_decode((string) env('MONEROO_METHODS_BY_CURRENCY', '{}'), true) ?: [],
            'return_url' => env('MONEROO_RETURN_URL', env('APP_BACKEND_URL', env('APP_URL', 'http://localhost:8000')).'/api/payments/moneroo/return'),
            'webhook_url' => env('MONEROO_WEBHOOK_URL', env('APP_BACKEND_URL', env('APP_URL', 'http://localhost:8000')).'/api/payments/webhook/moneroo'),
            'frontend_return_url' => env('MONEROO_FRONTEND_RETURN_URL', env('APP_FRONTEND_URL', env('FRONTEND_URL', 'http://localhost:3000')).'/checkout/return'),
        ],
    ],
    'kucoin' => [
        'base_url' => env('KUCOIN_BASE_URL', 'https://api.kucoin.tr'),
        'key' => env('KUCOIN_API_KEY'),
        'secret' => env('KUCOIN_API_SECRET'),
        'passphrase' => env('KUCOIN_API_PASSPHRASE'),
        'key_version' => env('KUCOIN_API_KEY_VERSION', '3'),
        'usd_xof_rate' => env('KUCOIN_USD_XOF_RATE', 610),
        'usdt_eur_rate' => env('KUCOIN_USDT_EUR_RATE', 0.92),
        'intent_expiry_minutes' => env('KUCOIN_PAYMENT_INTENT_EXPIRY_MINUTES', 45),
    ],
    'youtube' => [
        'key' => env('YOUTUBE_API_KEY'),
        'channel_id' => env('YOUTUBE_CHANNEL_ID'),
        'client_id' => env('YOUTUBE_CLIENT_ID'),
        'client_secret' => env('YOUTUBE_CLIENT_SECRET'),
        'redirect_uri' => env('YOUTUBE_REDIRECT_URI'),
        'frontend_url' => env('APP_FRONTEND_URL', env('FRONTEND_URL', 'http://localhost:3000')),
    ],
    'steam' => [
        'key' => env('STEAM_WEB_API_KEY'),
        'news_cache_minutes' => env('STEAM_NEWS_CACHE_MINUTES', 60),
        'news_apps' => [
            ['appid' => 730, 'name' => 'Counter-Strike 2', 'category' => 'FPS / Shooter'],
            ['appid' => 570, 'name' => 'Dota 2', 'category' => 'MOBA'],
            ['appid' => 578080, 'name' => 'PUBG', 'category' => 'Battle Royale'],
            ['appid' => 1172470, 'name' => 'Apex Legends', 'category' => 'Battle Royale'],
            ['appid' => 271590, 'name' => 'Grand Theft Auto V', 'category' => 'Action'],
            ['appid' => 1245620, 'name' => 'Elden Ring', 'category' => 'RPG'],
        ],
    ],
    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect_uri' => env('GOOGLE_REDIRECT_URI', env('APP_BACKEND_URL', env('APP_URL', 'http://localhost:8000')).'/api/auth/google/callback'),
        'frontend_url' => env('APP_FRONTEND_URL', env('FRONTEND_URL', 'http://localhost:3000')),
        'people_scopes' => array_values(array_filter(explode(' ', env('GOOGLE_PEOPLE_SCOPES', 'openid email profile https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email')))),
        'youtube_engagement_scopes' => array_values(array_filter(explode(' ', env('GOOGLE_YOUTUBE_ENGAGEMENT_SCOPES', 'https://www.googleapis.com/auth/youtube.force-ssl')))),
        'calendar' => [
            'id' => env('GOOGLE_TOURNAMENT_CALENDAR_ID'),
            'api_key' => env('GOOGLE_CALENDAR_API_KEY', env('GOOGLE_API_KEY')),
            'service_account_json' => env('GOOGLE_CALENDAR_SERVICE_ACCOUNT_JSON'),
            'timezone' => env('GOOGLE_TOURNAMENT_CALENDAR_TIMEZONE', 'UTC'),
            'slot_minutes' => env('TOURNAMENT_SLOT_MINUTES', 60),
            'step_minutes' => env('TOURNAMENT_SLOT_STEP_MINUTES', 60),
            'day_start' => env('TOURNAMENT_SLOT_DAY_START', '18:00'),
            'day_end' => env('TOURNAMENT_SLOT_DAY_END', '23:00'),
        ],
        'merchant' => [
            'account_id' => env('GOOGLE_MERCHANT_ACCOUNT_ID', '5814761746'),
            'data_source_id' => env('GOOGLE_MERCHANT_DATA_SOURCE_ID', '10678423802'),
            'service_account_json' => env('GOOGLE_MERCHANT_SERVICE_ACCOUNT_JSON'),
            'accounts_api_base_url' => env('GOOGLE_MERCHANT_ACCOUNTS_API_BASE_URL', 'https://merchantapi.googleapis.com/accounts/v1'),
            'api_base_url' => env('GOOGLE_MERCHANT_API_BASE_URL', 'https://merchantapi.googleapis.com/products/v1'),
            'language' => env('GOOGLE_MERCHANT_LANGUAGE', 'fr'),
            'feed_label' => env('GOOGLE_MERCHANT_FEED_LABEL', 'FR'),
            'channel' => env('GOOGLE_MERCHANT_CHANNEL', 'ONLINE'),
            'currency' => env('GOOGLE_MERCHANT_CURRENCY', 'EUR'),
            'shipping_countries' => array_values(array_filter(array_map('trim', explode(',', env('GOOGLE_MERCHANT_SHIPPING_COUNTRIES', 'AT,BE,BG,HR,CY,CZ,DK,EE,FI,FR,DE,GR,HU,IE,IT,LV,LT,LU,MT,NL,PL,PT,RO,SK,SI,ES,SE'))))),
            'default_image_url' => env('GOOGLE_MERCHANT_DEFAULT_IMAGE_URL', env('APP_FRONTEND_URL', env('FRONTEND_URL', 'https://www.astral4gamer.com')).'/android-chrome-512x512.png'),
            'default_brand' => env('GOOGLE_MERCHANT_DEFAULT_BRAND', 'Astral4Gamer'),
            'max_products' => env('GOOGLE_MERCHANT_MAX_PRODUCTS', 1000),
            'timeout' => env('GOOGLE_MERCHANT_TIMEOUT', 60),
            'retry_times' => env('GOOGLE_MERCHANT_RETRY_TIMES', 3),
            'retry_sleep' => env('GOOGLE_MERCHANT_RETRY_SLEEP', 1000),
            'sync_enabled' => env('GOOGLE_MERCHANT_SYNC_ENABLED', false),
            'sync_schedule' => env('GOOGLE_MERCHANT_SYNC_SCHEDULE', '03:20'),
        ],
    ],
    'blogger' => [
        'blog_id' => env('BLOGGER_BLOG_ID'),
        'auto_publish' => env('BLOGGER_AUTO_PUBLISH', true),
        'labels' => array_values(array_filter(array_map('trim', explode(',', env('BLOGGER_LABELS', 'Free Fire,Tournoi,Esport,Astral4Gamer'))))),
        'oauth_scopes' => array_values(array_filter(explode(' ', env('GOOGLE_BLOGGER_SCOPES', 'https://www.googleapis.com/auth/blogger')))),
    ],
    'openai' => [
        'key' => env('OPENAI_API_KEY'),
    ],
    'obs' => [
        'websocket_url' => env('OBS_WEBSOCKET_URL'),
        'password' => env('OBS_WEBSOCKET_PASSWORD'),
    ],
    'clerk' => [
        'issuer' => env('CLERK_JWT_ISSUER'),
        'secret_key' => env('CLERK_SECRET_KEY'),
    ],
];
