<?php

use App\Http\Controllers\Api\AdminController;
use App\Http\Controllers\Api\AdminAuthController;
use App\Http\Controllers\Api\AdminBlogPostController;
use App\Http\Controllers\Api\AdminIntegrationController;
use App\Http\Controllers\Api\AdminNotificationController;
use App\Http\Controllers\Api\AdminOrderController;
use App\Http\Controllers\Api\AdminProductController;
use App\Http\Controllers\Api\AdminResellerController;
use App\Http\Controllers\Api\AdminVideoController;
use App\Http\Controllers\Api\BlogPostController;
use App\Http\Controllers\Api\CommunityController;
use App\Http\Controllers\Api\DiamondDuelController;
use App\Http\Controllers\Api\FreeFireController;
use App\Http\Controllers\Api\FortniteController;
use App\Http\Controllers\Api\GenshinImpactController;
use App\Http\Controllers\Api\GoogleAuthController;
use App\Http\Controllers\Api\GuildController;
use App\Http\Controllers\Api\LiveController;
use App\Http\Controllers\Api\MissionController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OrderSupportController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PartnershipController;
use App\Http\Controllers\Api\PlayerController;
use App\Http\Controllers\Api\PublicProfileController;
use App\Http\Controllers\Api\PubgController;
use App\Http\Controllers\Api\ReplayController;
use App\Http\Controllers\Api\ResellerApiController;
use App\Http\Controllers\Api\ResellerAuthController;
use App\Http\Controllers\Api\ShopController;
use App\Http\Controllers\Api\SteamController;
use App\Http\Controllers\Api\TournamentController;
use App\Http\Controllers\Api\TournamentCalendarController;
use App\Http\Controllers\Api\UpcomingGameController;
use App\Http\Controllers\Api\UserMailboxController;
use Illuminate\Support\Facades\Route;

Route::middleware(['api', 'throttle:api'])->group(function () {
    Route::get('/public/freefire-profiles/{uid}', [PublicProfileController::class, 'showByFreeFireUid']);
    Route::get('/public/cod-profiles/{activisionId}', [PublicProfileController::class, 'showByCodActivisionId']);
    Route::get('/public/profiles/{username}', [PublicProfileController::class, 'show']);
    Route::get('/health', fn () => ['status' => 'ok', 'service' => 'nexy-api']);
    Route::get('/home', [ShopController::class, 'home']);
    Route::get('/products', [ShopController::class, 'products']);
    Route::get('/products/categories', [ShopController::class, 'categories']);
    Route::get('/products/{product}', [ShopController::class, 'product']);
    Route::post('/orders/guest', [ShopController::class, 'guestOrder']);
    Route::get('/orders/{order}/delivery', [ShopController::class, 'orderDelivery']);
    Route::post('/support/order-requests', [OrderSupportController::class, 'store'])->middleware('throttle:uid');
    Route::post('/partnership-requests', [PartnershipController::class, 'store'])->middleware('throttle:uid');
    Route::get('/bot/partnership-approvals', [PartnershipController::class, 'approvedForBot'])->middleware('throttle:api');
    Route::post('/bot/partnership-approvals/{partnershipRequest}/notified', [PartnershipController::class, 'markBotNotified'])->middleware('throttle:api');
    Route::post('/payments/moneroo/initiate', [PaymentController::class, 'initiateGuest']);
    Route::get('/payments/moneroo/return', [PaymentController::class, 'monerooReturn']);
    Route::post('/payments/webhook/{provider}', [PaymentController::class, 'webhook'])->middleware('signed.webhook');
    Route::post('/player/verify', [PlayerController::class, 'verify'])->middleware('throttle:uid');
    Route::post('/freefire/validate', [FreeFireController::class, 'validateUid'])->middleware('throttle:uid');
    Route::post('/freefire/profile', [FreeFireController::class, 'profile'])->middleware('throttle:uid');
    Route::post('/pubg/profile', [PubgController::class, 'profile'])->middleware('throttle:uid');
    Route::get('/pubg/matches', [PubgController::class, 'matches'])->middleware('throttle:uid');
    Route::get('/pubg/match', [PubgController::class, 'match'])->middleware('throttle:uid');
    Route::get('/pubg/leaderboard', [PubgController::class, 'leaderboard']);
    Route::post('/fortnite/profile', [FortniteController::class, 'profile'])->middleware('throttle:uid');
    Route::get('/fortnite/shop', [FortniteController::class, 'shop']);
    Route::get('/fortnite/news', [FortniteController::class, 'news']);
    Route::post('/freefire/visuals', [FreeFireController::class, 'visuals'])->middleware('throttle:uid');
    Route::get('/freefire/image', [FreeFireController::class, 'image'])->middleware('throttle:api');
    Route::get('/freefire/likes/quote', [FreeFireController::class, 'likesQuote']);
    Route::post('/freefire/likes/request', [FreeFireController::class, 'requestLikes'])->middleware('throttle:uid');
    Route::get('/freefire/redeem-codes', [FreeFireController::class, 'redeemCodes']);
    Route::post('/freefire/redeem-codes/claim', [FreeFireController::class, 'claimRedeemCode'])->middleware('throttle:uid');
    Route::get('/genshin/overview', [GenshinImpactController::class, 'overview']);
    Route::get('/genshin/catalog', [GenshinImpactController::class, 'catalog']);
    Route::get('/games/upcoming', [UpcomingGameController::class, 'index']);
    Route::get('/tournaments', [TournamentController::class, 'index']);
    Route::get('/tournaments/{tournament}', [TournamentController::class, 'show']);
    Route::get('/calendar/tournament-slots', [TournamentCalendarController::class, 'slots']);
    Route::get('/lives/current', [LiveController::class, 'current']);
    Route::get('/streams/current', [ReplayController::class, 'currentStream']);
    Route::get('/youtube/recent-videos', [ReplayController::class, 'recentYoutube']);
    Route::get('/replays', [ReplayController::class, 'index']);
    Route::get('/replays/{slug}', [ReplayController::class, 'show']);
    Route::get('/highlights', [ReplayController::class, 'highlights']);
    Route::get('/leaderboards', [PlayerController::class, 'leaderboards']);
    Route::get('/blog-posts', [BlogPostController::class, 'index']);
    Route::get('/blog-posts/{slug}', [BlogPostController::class, 'show']);
    Route::post('/admin/login', [AdminAuthController::class, 'login'])->middleware('throttle:uid');
    Route::post('/reseller/panel/login', [ResellerAuthController::class, 'login'])->middleware('throttle:uid');
    Route::get('/notifications/feed', [NotificationController::class, 'feed']);
    Route::get('/diamond-duels', [DiamondDuelController::class, 'index']);
    Route::get('/auth/google/redirect', [GoogleAuthController::class, 'redirect']);
    Route::get('/auth/google/callback', [GoogleAuthController::class, 'callback']);
    Route::get('/auth/steam/redirect', [SteamController::class, 'redirect']);
    Route::get('/auth/steam/callback', [SteamController::class, 'callback']);
    Route::get('/steam/profile', [SteamController::class, 'profile']);
    Route::get('/steam/news', [SteamController::class, 'news']);
    Route::get('/steam/achievements', [SteamController::class, 'achievements']);
    Route::get('/steam/player-achievements', [SteamController::class, 'playerAchievements']);
    Route::get('/steam/tf2/items', [SteamController::class, 'tf2Items']);
});

Route::middleware(['auth.reseller', 'throttle:api'])->prefix('reseller')->group(function () {
    Route::get('/panel/me', [ResellerAuthController::class, 'me']);
    Route::get('/panel/overview', [ResellerApiController::class, 'panelOverview']);
    Route::post('/panel/topup', [ResellerApiController::class, 'topup']);
    Route::post('/panel/api-keys/live', [ResellerApiController::class, 'regenerateLiveKey']);
    Route::get('/panel/orders', [ResellerApiController::class, 'orders']);
    Route::get('/panel/transactions', [ResellerApiController::class, 'transactions']);
    Route::get('/v1/categories', [ResellerApiController::class, 'categories']);
    Route::get('/v1/products', [ResellerApiController::class, 'products']);
    Route::get('/v1/products/{product}', [ResellerApiController::class, 'product']);
    Route::get('/v1/get-balance', [ResellerApiController::class, 'balance']);
    Route::post('/v1/order/add-order', [ResellerApiController::class, 'addOrder']);
    Route::get('/v1/order/get-order', [ResellerApiController::class, 'getOrder']);
});

Route::middleware(['auth:sanctum', 'throttle:api'])->group(function () {
    Route::post('/orders', [ShopController::class, 'order']);
    Route::post('/payments/initiate', [PaymentController::class, 'initiate']);
    Route::post('/payments/{payment}/verify', [PaymentController::class, 'verify']);
    Route::get('/user/tournaments', [TournamentController::class, 'mine']);
    Route::post('/tournament-requests', [TournamentController::class, 'requestCreation']);
    Route::post('/tournaments/{tournament}/register', [TournamentController::class, 'register']);
    Route::post('/community/profile-share', [CommunityController::class, 'shareProfile'])->middleware('throttle:uid');
    Route::post('/community/team-search', [CommunityController::class, 'searchTeam'])->middleware('throttle:uid');
    Route::post('/community/clips', [CommunityController::class, 'shareClip'])->middleware('throttle:uid');
    Route::post('/community/youtube/like', [CommunityController::class, 'likeYoutubeVideo'])->middleware('throttle:uid');
    Route::post('/community/youtube/subscribe', [CommunityController::class, 'subscribeYoutube'])->middleware('throttle:uid');
    Route::post('/community/youtube/share', [CommunityController::class, 'shareYoutubeVideo'])->middleware('throttle:uid');
    Route::post('/guilds', [GuildController::class, 'store']);
    Route::post('/guilds/{guild}/join', [GuildController::class, 'join']);
    Route::post('/missions/{mission}/claim', [MissionController::class, 'claim']);
    Route::post('/user/freefire/profile-refresh', [FreeFireController::class, 'requestProfileRefresh'])->middleware('throttle:uid');
    Route::get('/user/google-profile', [GoogleAuthController::class, 'profile']);
    Route::get('/user/steam/redirect', [SteamController::class, 'redirect']);
    Route::get('/user/steam-profile', [SteamController::class, 'me']);
    Route::get('/user/astral-mails', [UserMailboxController::class, 'index']);
    Route::patch('/user/astral-mails/{message}/read', [UserMailboxController::class, 'markRead']);
    Route::get('/user/diamond-duels', [DiamondDuelController::class, 'mine']);
    Route::post('/diamond-duels', [DiamondDuelController::class, 'store'])->middleware('throttle:uid');
    Route::post('/diamond-duels/{duel}/join', [DiamondDuelController::class, 'join'])->middleware('throttle:uid');
    Route::post('/diamond-duels/{duel}/accept', [DiamondDuelController::class, 'accept'])->middleware('throttle:uid');
    Route::post('/diamond-duels/{duel}/decline', [DiamondDuelController::class, 'decline'])->middleware('throttle:uid');
    Route::delete('/user/google-disconnect', [GoogleAuthController::class, 'disconnect']);
});

Route::middleware(['auth:sanctum', 'can:admin'])->prefix('admin')->group(function () {
    Route::apiResource('tournaments', TournamentController::class)->except(['index', 'show']);
    Route::post('/tournaments/{tournament}/results', [TournamentController::class, 'submitResult']);
    Route::post('/tournaments/{tournament}/complete', [TournamentController::class, 'complete']);
    Route::post('/tournaments/{tournament}/reward-claimed', [TournamentController::class, 'claimReward']);
    Route::post('/suppliers/item4gamer/sync', [ShopController::class, 'syncItem4Gamer']);
    Route::get('/suppliers/item4gamer/balance', [ShopController::class, 'item4GamerBalance']);
    Route::get('/suppliers/item4gamer/orders', [ShopController::class, 'item4GamerOrder']);
    Route::post('/suppliers/fazercards/sync', [ShopController::class, 'syncFazerCards']);
    Route::get('/suppliers/fazercards/balance', [ShopController::class, 'fazerCardsBalance']);
    Route::get('/suppliers/fazercards/orders', [ShopController::class, 'fazerCardsOrder']);
    Route::get('/analytics', [AdminController::class, 'analytics']);
    Route::get('/orders/manual', [AdminOrderController::class, 'manualOrders']);
    Route::patch('/orders/{order}/manual-status', [AdminOrderController::class, 'updateManualStatus']);
    Route::get('/products/manage', [AdminProductController::class, 'index']);
    Route::patch('/products/{product}', [AdminProductController::class, 'update']);
    Route::get('/resellers', [AdminResellerController::class, 'index']);
    Route::get('/resellers/requests', [AdminResellerController::class, 'requests']);
    Route::post('/resellers/requests/{partnershipRequest}/approve', [AdminResellerController::class, 'approve']);
    Route::patch('/resellers/{partner}', [AdminResellerController::class, 'update']);
    Route::post('/resellers/{partner}/suspend', [AdminResellerController::class, 'suspend']);
    Route::post('/resellers/{partner}/activate', [AdminResellerController::class, 'activate']);
    Route::get('/sections/{section}', [AdminController::class, 'section']);
    Route::get('/logs', [AdminController::class, 'logs']);
    Route::post('/notifications/promotion', [AdminNotificationController::class, 'promotion']);
    Route::get('/integrations/google', [AdminIntegrationController::class, 'google']);
    Route::get('/integrations/blog', [AdminIntegrationController::class, 'blog']);
    Route::apiResource('blog-posts', AdminBlogPostController::class);
    Route::post('/blog-posts/{blogPost}/publish-to-blogger', [AdminBlogPostController::class, 'publishToBlogger']);
    Route::post('/blog-posts/generate-from-tournament/{tournament}', [AdminBlogPostController::class, 'generateFromTournament']);
    Route::post('/blog-posts/generate-from-replay/{replay}', [AdminBlogPostController::class, 'generateFromReplay']);
    Route::post('/blog-posts/generate-weekly-summary', [AdminBlogPostController::class, 'generateWeeklySummary']);
    Route::get('/youtube/status', [AdminVideoController::class, 'youtubeStatus']);
    Route::get('/youtube/redirect', [AdminVideoController::class, 'youtubeRedirect']);
    Route::get('/youtube/callback', [AdminVideoController::class, 'youtubeCallback']);
    Route::post('/youtube/lives', [AdminVideoController::class, 'createLive']);
    Route::post('/youtube/videos/sync', [AdminVideoController::class, 'syncVideo']);
    Route::post('/streams/{stream}/status', [AdminVideoController::class, 'updateStreamStatus']);
    Route::post('/replays/{replay}/analyze', [AdminVideoController::class, 'analyzeReplay']);
    Route::patch('/replay-moments/{moment}', [AdminVideoController::class, 'updateMoment']);
    Route::post('/replay-moments/{moment}/highlight', [AdminVideoController::class, 'generateHighlight']);
    Route::post('/streams/{stream}/markers', [AdminVideoController::class, 'markStreamMoment']);
    Route::get('/obs/status', [AdminVideoController::class, 'obsStatus']);
    Route::post('/obs/{command}', [AdminVideoController::class, 'obsCommand']);
});
